[package]
name = "aoc2024"
edition = "2021"

[profile.release]
overflow-checks = true

[[bin]]
name = "16"
path = "16.rs"

[[bin]]
name = "18"
path = "18.rs"

[[bin]]
name = "19"
path = "19.rs"

[[bin]]
name = "20"
path = "20.rs"

